build:
  info: "default-config"

loans:
  message: "Welcome to loans related default APIs "
  contactDetails:
    name: "Yogindersingh - Developer"
  onCallSupport:
    - +91 1234567890
    - +91 0987654321