server:
  port: 9001

application:
  name: "@project.artifactId@"
  version: "@project.version@"

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      #default file value is schema.sql for schema and data.sql for datafile
      schema-locations: classpath:schemacustom.sql

build:
  info: "@project.version@"

cards:
  message: "Welcome to accounts related local APIs "
  contactDetails:
    name: "Yogindersingh - Developer"
  onCallSupport:
    - +91 1234567890
    - +91 0987654321