spring:
  application:
    name: spring-eureka-server
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071}

application:
  name: "@project.artifactId@"
  version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
