{{- if .Values.loans.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-loans
  labels:
    {{- include "java-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/name: loans
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loans
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loans
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: loans
          image: "{{ .Values.loans.image.repository }}:{{ .Values.loans.image.tag }}"
          imagePullPolicy: {{ .Values.loans.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          env:
            {{- include "java-microservices.configServerEnv" . | nindent 12 }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.loans.env.datasourceUrl | quote }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            {{- toYaml .Values.loans.resources | nindent 12 }}
{{- end }}
