apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "java-microservices.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
  keycloak-admin-password: {{ .Values.keycloak.auth.adminPassword | b64enc | quote }}
