services:
  network-service:
    networks:
      - common-network

  microservice-base-config:
    extends:
      service: network-service
    mem_limit: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-2.22.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://spring-cloud-config-server:8071/
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://spring-eureka-server:8070/eureka/