server:
  port: 8080

application:
  name: "@project.artifactId@"
  version: "@project.version@"

spring:
  application:
    name: "accounts"
  profiles:
    active: prod
  datasource:
    username: root
    password: root@1234
    url: jdbc:mysql://localhost:3306/accountsDb?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
  #    //h2 related configurations
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  sql:
    init:
      #default file value is schema.sql for schema and data.sql for datafile
      schema-locations: classpath:schemacustom.sql
      mode: always
  config:
    import: "configserver:http://localhost:8071"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
#      data-locations: classpath:datacustom.sql

management:
  endpoints:
    web:
      exposure:
        include: "*"