server:
  port: 8080

application:
  name: "@project.artifactId@"
  version: "@project.version@"

spring:
  application:
    name: "accounts"
  profiles:
    active: prod
  datasource:
    username: root
    password: root@1234
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/accountsDb?createDatabaseIfNotExist=true}
  jpa:
    show-sql: true
  #    //h2 related configurations
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  sql:
    init:
      #default file value is schema.sql for schema and data.sql for datafile
      schema-locations: classpath:schemacustom.sql
      mode: always
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071}
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
#      data-locations: classpath:datacustom.sql

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8070/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
    prometheus:
      access: unrestricted
  info:
    env:
      enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
info:
  app:
    name: "accounts"
    description: "Accounts microservice"
    version: "@project.version@"

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state:
          seconds: 1

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"