version: "2"

services:
  accounts:
    image: yogindersingh634/accounts:0.0.1-SNAPSHOT
    container_name: accounts-ms
    ports:
      - "8080:8080"
    mem_limit: 700mb
    networks:
      - common-network
  cards:
    image: yogindersingh634/cards:0.0.1-SNAPSHOT
    container_name: cards-ms
    ports:
      - "9001:9001"
    mem_limit: 700mb
    networks:
      - common-network
  loans:
    image: yogindersingh634/loans:0.0.1-SNAPSHOT
    container_name: loans-ms
    ports:
      - "8090:8090"
    mem_limit: 700mb
    networks:
      - common-network

networks:
  common-network:
    driver: bridge