services:
  mysqlDb:
    image: mysql:latest
    hostname: mysqlDb
    container_name: mysql_microservices
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    extends:
      file: common-config.yaml
      service: network-service
    environment:
      MYSQL_ROOT_PASSWORD: root@1234

  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    mem_limit: 700mb
    healthcheck:
      test: rabbitmq-diagnostics check_running
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    extends:
      file: common-config.yaml
      service: network-service

  spring-cloud-config-server:
    image: yogindersingh634/spring-cloud-config-server:0.0.1-SNAPSHOT
    hostname: spring-cloud-config-server
    container_name: spring-cloud-config-server
    ports:
      - "8071:8071"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8071/accounts/default | grep propertySources || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      rabbitmq:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-base-config

  spring-eureka-server:
    image: yogindersingh634/spring-eureka-server:0.0.1-SNAPSHOT
    hostname: spring-eureka-server
    container_name: spring-eureka-server
    ports:
      - "8070:8070"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8070/actuator/health | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      spring-cloud-config-server:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-base-config
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://spring-cloud-config-server:8071/

  accounts:
    image: yogindersingh634/accounts:0.0.1-SNAPSHOT
    container_name: accounts-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      spring-cloud-config-server:
        condition: service_healthy
      mysqlDb:
        condition: service_healthy
      spring-eureka-server:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlDb:3306/accountsDb?createDatabaseIfNotExist=true

  cards:
    image: yogindersingh634/cards:0.0.1-SNAPSHOT
    container_name: cards-ms
    ports:
      - "9001:9001"
    healthcheck:
      test: "curl --fail --silent localhost:9001/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      spring-cloud-config-server:
        condition: service_healthy
      mysqlDb:
        condition: service_healthy
      spring-eureka-server:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlDb:3306/cardsDb?createDatabaseIfNotExist=true

  loans:
    image: yogindersingh634/loans:0.0.1-SNAPSHOT
    container_name: loans-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      spring-cloud-config-server:
        condition: service_healthy
      mysqlDb:
        condition: service_healthy
      spring-eureka-server:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlDb:3306/loansDb?createDatabaseIfNotExist=true

  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass password --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  spring-cloud-gateway-server:
    image: yogindersingh634/spring-cloud-gateway-server:0.0.1-SNAPSHOT
    container_name: spring-cloud-gateway-server
    ports:
      - "8072:8072"
    depends_on:
      loans:
        condition: service_healthy
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_DATA_REDIS_HOST: redis
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

networks:
  common-network:
    driver: bridge