services:
  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    mem_limit: 700mb
    healthcheck:
      test: rabbitmq-diagnostics check_running
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    extends:
      file: common-config.yaml
      service: network-service

  spring-cloud-config-server:
    image: yogindersingh634/spring-cloud-config-server:0.0.1-SNAPSHOT
    hostname: spring-cloud-config-server
    container_name: spring-cloud-config-server
    ports:
      - "8071:8071"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8071/accounts/default | grep propertySources || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      rabbitmq:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-base-config

  accounts:
    image: yogindersingh634/accounts:0.0.1-SNAPSHOT
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      spring-cloud-config-server:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

  cards:
    image: yogindersingh634/cards:0.0.1-SNAPSHOT
    container_name: cards-ms
    ports:
      - "9001:9001"
    depends_on:
      spring-cloud-config-server:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

  loans:
    image: yogindersingh634/loans:0.0.1-SNAPSHOT
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      spring-cloud-config-server:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

networks:
  common-network:
    driver: bridge