{{- if .Values.gateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    {{- include "java-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/name: spring-cloud-gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-cloud-gateway-server
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-cloud-gateway-server
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: spring-cloud-gateway-server
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8072
              protocol: TCP
          env:
            {{- include "java-microservices.configServerEnv" . | nindent 12 }}
            - name: SPRING_DATA_REDIS_HOST
              value: {{ .Values.gateway.env.redisHost | quote }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWT_SET_URI
              value: {{ .Values.gateway.env.jwtSetUri | quote }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
{{- end }}
