{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-gateway-server
  labels:
    {{- include "java-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/name: spring-cloud-gateway-server
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.gateway.service.type "NodePort") .Values.gateway.service.nodePort }}
      nodePort: {{ .Values.gateway.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: spring-cloud-gateway-server
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
