{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    {{- include "java-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/name: mysql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
