spring:
  application:
    name: spring-cloud-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
server:
  port: 8071

application:
  name: "@project.artifactId@"
  version: "@project.version@"

